#%RAML 1.0 DataType
type: object
properties:
  ProductID: integer
  ProductName: string
  SupplierID: integer
  CategoryID: integer
  QuantityPerUnit?: string
  UnitPrice?: integer
  UnitsInStock?: integer
  UnitsOnOrder?: integer
  ReorderLevel?: integer
  Discontinued?: integer
