#%RAML 1.0 DataType

type: object
properties: 
  CustomerID:
    type: string
    required: false
  EmployeeID:
    type: integer
    required: false
  OrderDate:
    type: date-only
    required: false
  RequiredData:
    type: date-only
    required: false
  ShippedDate: 
    type: date-only
    required: false
  ShipVia: 
    type: integer
    required: false
  Freight:
    type: integer
    required: false
  ShipName:
    type: string
    required: false
  ShipAddress:
    type: string
    required: false
  ShipCity:
    type: string
    required: false
  ShipRegion:
    type: string
    required: false
  ShipPostalCode:
    type: string
    required: false
  ShipCountry:
    type: string
    required: false