#%RAML 1.0
title: Order SAPI
version: 1.0

types:
  order: !include DataTypes/order.raml

/orders:
  post:
    description: Insert a new order into the database
    body:
      application/json: 
        type: order
        example: !include Examples/POST-example.raml
    responses:
      201:
        body:
          application/json:
             example: 
              {"orderID": 10253} 
  /employee:              
    /{employeeID}:
      get:
        description: Get a list of orders for a specific employee
        responses:
          200:
            body:
              application/json:
                type: order[] 
                examples: !include Examples/GET-example.raml    

  /customer:
    /{customerID}:
      get:
        description: Get a list of orders for a specific customer 
        responses:
          200:
            body:
              application/json:
                type: order []
                examples: !include Examples/GET-example.raml
/shipAddress:
  get:
    queryParameters:
      customerID:
    responses:
      200:
        body:
          application/json:
            example:
             {"shipAddress": "Maddison Scuare"}
