#%RAML 1.0 NamedExample

value:
  CustomerID: HILAA
  CompanyName: HILARION-Abastos
  ContactName: Carlos Hernndez
  ContactTitle: Sales Representative
  Address: Carrera 22 con Ave. Carlos Soublette #8-35
  City: San Cristbal
  Region: Tchira
  PostalCode: 5022
  Country: Venezuela
  Phone: (5) 555-1340
  Fax: (5) 555-1948