#%RAML 1.0 orders-example
value:
  - 
    OrderID: 12345
    CustomerID:  ALFKI
    EmployeeID: 1
    OrderDate: 2022-12-01
    RequiredDate: 2022-12-05
    ShippedDate: 2022-12-10
    ShipVia: 2
    Freight: 6000
    ShipName: Simons Bistro
    ShipAddress: 2817 Milton Dr
    ShipCity: Spokane
    ShipRegion: WA
    ShipPostalCode: 123-573
    ShipCountry: USA
  - 
    OrderID: 54321
    CustomerID:  ANTON
    EmployeeID: 3
    OrderDate: 2022-12-10
    RequiredDate: 2022-12-12
    ShippedDate: 2022-12-14
    ShipVia: 1
    Freight: 8000
    ShipName: Apple Inc
    ShipAddress: 20 First Ave
    ShipCity: New York
    ShipRegion: NY
    ShipPostalCode: 123-123
    ShipCountry: USA