http:
  port: "8084"
  
db: 
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"
  database: "northwind"
  
requestext:
  host: "localhost"
  port: "8081"
  
requestown:
  host: "localhost"
  port: "8084"

