http: 
  port: "8086"
  
db: 
  host: "20.224.50.155"
  port: "3306"
  user: "group04"
  password: "@Br1ghtsGr0up04!"
  database: "northwind04"
  
requestss:
  host: "localhost"
  port: "8084"
  
requestoffs:
  host: "localhost"
  port: "8083"
  
requestps:
  host: "localhost"
  port: "8087"
  
requestords:
  host: "localhost"
  port: "8085"