http:
  port: "8086"
  
db:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"
  database: "northwind"  
  
requestss:
  host: "localhost"
  port: "8084"
  
requestoffs:
  host: "localhost"
  port: "8083"
  
requestps:
  host: "localhost"
  port: "8087"