#%RAML 1.0 Customer-example
value: 
  
  CustomerID: ANTON
  CompanyName: Antonio Moreno Taquera
  ContactName: Antonio Moreno
  ContactTitle: Owner
  Address: Mataderos 2312
  City: Mexico City
  PostalCode: 05023 
  Country: Mexico
  Region: MA
  Phone: (5) 555-3932
  Fax: 222.222.222