#%RAML 1.0
title: northwind customer exp API


types:
  Customer: !include Datatypes/customer.raml
  Offer: !include Datatypes/offer.raml
  Product: !include Datatypes/product.raml

/customers:
  get:
    responses:
      200:
        body:
          application/json: 
            type: Customer[]
            examples:
              output: !include Examples/customers.raml
  post:
    body:
      application/json:
        type: Customer
        examples:
          input: !include Examples/customer.raml
    responses:
      201:
        body:
          application/json:
            example:
              value: "Customer added successfully"
  /{ID}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Customer
              example: !include Examples/customer.raml
/offers:
  post:
    body:
      application/json:
        type: Offer
        example: !include Examples/offer-post.raml
    responses:
      201:
        body:
          application/json:
            example:
              {"offerID": 12345}
  /{ID}:
    get:
      queryParameters:
        status:
          enum:
            - pending
            - proposed
            - accepted
            - rejected
            - out of stock
            - shipped
      responses:
        200:
          body:
            application/json:
              type: Offer[]
              examples: !include Examples/offers-by-status.raml
    patch:
      body:
        application/json:
          type: Offer
          example: !include Examples/offer-patch.raml
      responses:
        200:
          body:
            application/json:
              example:
                value: "Offer status = ACCEPTED"

/products: 
  get: 
    responses:
      200:
        body:
          application/json:
            type: Product[]
            examples: !include Examples/products.raml
              
            
    
    
            
  