#%RAML 1.0 DataType

type: object
properties: 
  OrderID?: integer
  CustomerID?: string
  EmployeeID?: integer
  OrderDate?: date-only
  RequiredDate?: date-only
  ShippedDate?: date-only
  ShipVia?: integer
  Freight?: integer
  ShipName?: string
  ShipAddress?: string
  ShipCity?: string
  ShipRegion?: string
  ShipPostalCode?: string
  ShipCountry?: string