#%RAML 1.0 NamedExample
value:
  OfferID: 1
  Status: pending
  DateCreated: 2022-12-13
  DateApproved: 2022-12-16
  EmployeeID: 7
  CustomerID: ALKWE
  ProductID: 23
  Quantity: 3
  OrderID: 11086
  TotalPrice: 30.00
  PriceDiscount: 0
  PaymentTransactionID: 9