#%RAML 1.0 NamedExample
value:
  -
    OfferID: 1
    Status: accepted
    DateCreated: 2022-12-13T16:41:41Z
    DateApproved: 2022-12-16T12:41:41Z
    EmployeeID: 5
    CustomerID: ALKWE
    ProductID: 23
    Quantity: 3
    OrderID: 11086
    TotalPrice: 30.00
    PriceDiscount: 0
    PaymentTransactionID: 12
  -
    OfferID: 2
    Status: accepted
    DateCreated: 2022-12-16T08:41:41Z
    DateApproved: 2022-12-19T11:41:41Z
    EmployeeID: 5
    CustomerID: ALKWE
    ProductID: 23
    Quantity: 5
    OrderID: 11078
    TotalPrice: 400.00
    PriceDiscount: 0
    PaymentTransactionID: 6