#%RAML 1.0
title: Product SAPI

types: 
  product: !include Datatypes/product.raml

/products:
  get:
    responses:
      200:
        body:
          application/json:
            type: product[]
            examples: !include Examples/products.raml
  /{ID}:
    get: 
      responses:
        200:
          body:
            application/json:
              type: product
              example: !include Examples/productByID.raml

  /price:
    get:
      queryParameters:
        offerID:
      responses:
        200:
          body:
            application/json:
              example:
                {"UnitPrice": 200}

  /unitsInStock:
    get:
      queryParameters:
        offerID:
      responses:
        200:
          body:
            application/json:
              example:
                {"UnitsInStock": 17}
                

              
      