http:
  port: "8080"
  
requestcs: 
  host: "localhost"
  port: "8082"
  
requestordp:
  host: "localhost"
  port: "8086"
  
requestoffs:
  host: "localhost"
  port: "8083"
  
requestps:
  host: "localhost"
  port: "8087"
  
requestords:
  host: "localhost"
  port: "8085"
  

  
